# Generated by Django 5.0.1 on 2025-10-28 12:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo único para identificar la consulta', max_length=255, unique=True, verbose_name='Nombre de la consulta')),
                ('descripcion', models.TextField(blank=True, help_text='Explicación de qué hace esta consulta y para qué sirve', verbose_name='Descripción')),
                ('select_clause', models.TextField(help_text='Campos a seleccionar con sus alias. Ej: a.Nombre AS Producto, p.Precio AS PrecioUnitario', verbose_name='Cláusula SELECT')),
                ('from_clause', models.TextField(help_text='Tabla base y JOINs. Ej: FROM dbo.Precios AS p INNER JOIN dbo.Articulos AS a ON p.id_articulo = a.id', verbose_name='Cláusula FROM')),
                ('where_clause', models.TextField(blank=True, help_text='Condiciones con parámetros dinámicos. Ej: WHERE a.Estado = %1 AND p.Precio > %2', verbose_name='Cláusula WHERE')),
                ('activa', models.BooleanField(default=True, help_text='Solo las consultas activas están disponibles para usuarios finales', verbose_name='Consulta activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('creado_por', models.CharField(blank=True, help_text='Usuario que creó esta consulta', max_length=100, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Consulta Dinámica',
                'verbose_name_plural': 'Consultas Dinámicas',
                'db_table': 'dynamic_queries',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activa'], name='dynamic_que_activa_36d0ae_idx'), models.Index(fields=['nombre'], name='dynamic_que_nombre_4d541b_idx'), models.Index(fields=['-fecha_modificacion'], name='dynamic_que_fecha_m_8e8b8a_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(help_text='Usuario que ejecutó la consulta', max_length=100, verbose_name='Usuario')),
                ('parametros_enviados', models.JSONField(default=dict, help_text='Valores de parámetros utilizados en la ejecución', verbose_name='Parámetros enviados')),
                ('total_resultados', models.IntegerField(default=0, help_text='Número de filas retornadas por la consulta', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total de resultados')),
                ('tiempo_ejecucion', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tiempo de ejecución (segundos)')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ejecución')),
                ('exitosa', models.BooleanField(default=True, verbose_name='Ejecución exitosa')),
                ('mensaje_error', models.TextField(blank=True, help_text='Descripción del error si la ejecución falló', verbose_name='Mensaje de error')),
                ('sql_ejecutado', models.TextField(blank=True, help_text='Query final que fue ejecutado (para debugging)', verbose_name='SQL ejecutado')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ejecuciones', to='queries.dynamicquery', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Ejecución de Consulta',
                'verbose_name_plural': 'Ejecuciones de Consultas',
                'db_table': 'query_executions',
                'ordering': ['-fecha_ejecucion'],
                'indexes': [models.Index(fields=['-fecha_ejecucion'], name='query_execu_fecha_e_ec6657_idx'), models.Index(fields=['query', '-fecha_ejecucion'], name='query_execu_query_i_9ad832_idx'), models.Index(fields=['usuario', '-fecha_ejecucion'], name='query_execu_usuario_637da4_idx'), models.Index(fields=['exitosa'], name='query_execu_exitosa_e2b55a_idx')],
            },
        ),
        migrations.CreateModel(
            name='QueryParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_interno', models.CharField(help_text='Nombre técnico del campo. Ej: estado_articulo, precio_minimo', max_length=100, verbose_name='Nombre interno')),
                ('etiqueta_usuario', models.CharField(help_text='Texto que verá el usuario final. Ej: Estado del Artículo, Precio Mínimo', max_length=255, verbose_name='Etiqueta para usuario')),
                ('tipo_dato', models.CharField(choices=[('texto', 'Texto'), ('numero', 'Número Entero'), ('decimal', 'Número Decimal'), ('fecha', 'Fecha'), ('boolean', 'Sí/No')], default='texto', max_length=20, verbose_name='Tipo de dato')),
                ('orden', models.IntegerField(default=0, help_text='Define el orden en el formulario (menor número aparece primero)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orden de aparición')),
                ('visible', models.BooleanField(default=True, help_text='Si está desmarcado, el parámetro no se mostrará en el formulario', verbose_name='Visible para usuario final')),
                ('requerido', models.BooleanField(default=False, help_text='Si está marcado, el usuario debe proporcionar un valor', verbose_name='Campo obligatorio')),
                ('valor_por_defecto', models.CharField(blank=True, help_text='Valor inicial del campo (opcional)', max_length=255, verbose_name='Valor por defecto')),
                ('placeholder', models.CharField(blank=True, help_text='Ejemplo o descripción breve que aparece en el campo. Ej: Ingrese un valor mayor a 0', max_length=255, verbose_name='Texto de ayuda')),
                ('posicion_where', models.IntegerField(help_text='Número que corresponde al %N en la cláusula WHERE. Ej: 1 para %1, 2 para %2', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Posición en WHERE')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parametros', to='queries.dynamicquery', verbose_name='Consulta')),
            ],
            options={
                'verbose_name': 'Parámetro de Consulta',
                'verbose_name_plural': 'Parámetros de Consultas',
                'db_table': 'query_parameters',
                'ordering': ['query', 'orden'],
                'indexes': [models.Index(fields=['query', 'orden'], name='query_param_query_i_35a587_idx'), models.Index(fields=['query', 'visible'], name='query_param_query_i_1dd5b4_idx')],
                'unique_together': {('query', 'nombre_interno'), ('query', 'posicion_where')},
            },
        ),
    ]
